LPS-181043
danvb112/liferay-portal pull request #53
Opened 2023-04-06 15:57 UTC by danvb112

2023-04-06 15:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-06 15:59 UTC, danvb112 commented
ci:test:sf

2023-04-06 16:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4224/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4224/jenkins-report.html">here</a>.</b></p>

2023-04-06 16:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/00d2e4f4b68de84bdade6a1c7e30bc9e9d3a56d2">00d2e4f4b68de84bdade6a1c7e30bc9e9d3a56d2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/danvb112/liferay-portal/tree/LPS-181043">LPS-181043</a><br/>Branch GIT ID: <a href="https://github.com/danvb112/liferay-portal/commit/e632c6f9cfc5a5f8441ad1a32fdc487d886c8326">e632c6f9cfc5a5f8441ad1a32fdc487d886c8326</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4224/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4224/jenkins-report.html">here</a>.</h5></details></html>

2023-04-06 16:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4224/">test-portal-source-format#4224</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4224/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/danvb112/liferay-portal/pull/53">danvb112#53</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2260420233">[master] ci:test:sf - danvb112 &gt; danvb112 - PR#53 - 2023-04-06[09:00:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/15824/">publish-testray-report#15824</a><br/></div></div>

2023-04-10 17:54 UTC, danvb112 commented
ci:test:sf

2023-04-10 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6127/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6127/jenkins-report.html">here</a>.</b></p>

2023-04-10 17:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/461db93292a657f8ec78696f4c382587b7dd1915">461db93292a657f8ec78696f4c382587b7dd1915</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/danvb112/liferay-portal/tree/LPS-181043">LPS-181043</a><br/>Branch GIT ID: <a href="https://github.com/danvb112/liferay-portal/commit/7c9511c07be2c37a966e23834b897fc5ea5bdeea">7c9511c07be2c37a966e23834b897fc5ea5bdeea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6127/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6127/jenkins-report.html">here</a>.</h5></details></html>

2023-04-10 18:01 UTC, danvb112 commented
ci:test:sf

2023-04-10 18:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5305/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5305/jenkins-report.html">here</a>.</b></p>

2023-04-10 18:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/461db93292a657f8ec78696f4c382587b7dd1915">461db93292a657f8ec78696f4c382587b7dd1915</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/danvb112/liferay-portal/tree/LPS-181043">LPS-181043</a><br/>Branch GIT ID: <a href="https://github.com/danvb112/liferay-portal/commit/b057bb188432a9f9943fd20834dcd004fc54f69f">b057bb188432a9f9943fd20834dcd004fc54f69f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5305/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5305/jenkins-report.html">here</a>.</h5></details></html>

2023-04-10 18:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5305/">test-portal-source-format#5305</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5305/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/danvb112/liferay-portal/pull/53">danvb112#53</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2263279269">[master] ci:test:sf - danvb112 &gt; danvb112 - PR#53 - 2023-04-10[11:02:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/20215/">publish-testray-report#20215</a><br/></div></div>

2023-04-10 18:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6127/">test-portal-source-format#6127</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6127/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/danvb112/liferay-portal/pull/53">danvb112#53</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2263302920">[master] ci:test:sf - danvb112 &gt; danvb112 - PR#53 - 2023-04-10[10:55:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/23370/">publish-testray-report#23370</a><br/></div></div>

2023-04-11 15:58 UTC, naraandrade commented
Just started reviewing :)

2023-04-11 16:17 UTC, naraandrade requested changes

2023-04-11 16:17 UTC, naraandrade commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/icons/business-center.svg
@danvb112 Please, avoid using svg files. You can use png files instead.

2023-04-11 16:27 UTC, naraandrade commented
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/133166

2023-04-11 16:27 UTC, closed without merging